language: generic
sudo: required
services:
  - docker  #tell trivis that hey Travis, we need a copy of docker ready to go

before_install:
  - docker build -t rrallvv/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true rrallvv/docker-react npm run test
